baseURL: http://ac-renovation.com
languageCode: fr-FR
title: AC RENOVATION
theme: hugo-fresh
disableKinds: [taxonomy]

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  description: "AC RENOVATION  | Expert en travaux de couverture, toiture, charpente, zinguerie et isolation en Île de France."
  openGraph: true
  navbarlogo:
    image: logos/ac-renovation-latest-sigma.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: "AC RENOVATION"
    subtitle: "Couverture | Toiture | Charpente | Zinguerie | Isolation | Expert en travaux de couverture, toiture, charpente, zinguerie et isolation en Île de France."
    # see themes/hugo-fresh/layouts/partials/hero-body.html to change
    buttontext: +33 7 59 20 00 34
    # buttonlink: "tel:+33759200034"
    image: logos/ac-renovation-latest-sigma.svg

  navbar:
  - title: AC RENOVATION
    url: /
  - title: Interventions
    sublinks:
    - title: Couverture
      url: /couverture
    - title: Toiture
      url: /toiture
    - title: Charpente
      url: /charpente
    - title: Zinguerie
      url: /zinguerie
    - title: Isolation
      url: /isolation
    - title: Gouttières
      url: /gouttieres
  - title: Prestations
    sublinks:
    - title: Interventions
      url: /interventions
    - title: Urgence
      url: /urgence
    - title: Diagnostic
      url: /diagnostic
    - title: Entretien & Réparation
      url: /entretien-reparation
  - title: Actualités
    url: /actualite
  section1:
    title: Nos prestations toitures
    subtitle: sur rendez-vous ou en urgence
    tiles:
      - title: Interventions
        icon: intervention
        text: Nos champs d'intervention pour votre toiture
        url: /interventions
        buttonText: Nos interventions
      - title: Urgence
        icon: danger
        text: Sinistres et/ou événements météorologiques
        url: /urgence
        buttonText: Urgence
      - title: Diagnostic
        icon: magnifying
        text: Recherche, analyse, identification et audit
        url: /diagnostic
        buttonText: Diagnostic
      - title: Entretien & Réparation
        icon: house-reparation
        text: Entretien et réparation des défauts de toitures
        url: /entretien-reparation
        buttonText: Entretien & Réparation
  section4:
    title: Ils nous ont fait confiance
    subtitle: pour toutes leurs urgences, réparations et travaux, voici leur retour
    clients:
    - name: Mat SERRANT
      quote: "Très pro et à l'écoute. Travail soigné avec respect des délais. Merci pour la réactivité."
      job: Client AC RENOVATION
      img: 2
    - name: Jean DUPRAS
      quote: "Ils sont sérieux et fiables. Ils proposent des solutions adaptées. On est en relation avec une équipe dynamique et à l'écoute."
      job: Client AC RENOVATION
      img: 2
    - name: Sylvie RAY
      quote: "A l'écoute, avec un vrai suivi des interventions et un travail de qualité. Je recommande en toute confiance."
      job: Cliente AC RENOVATION
      img: 1
  section5:
    title: Intervention rapide. Devis gratuit pour vos travaux de couverture, toiture, charpente, zinguerie et isolation.
    buttonText: Envoyer
    action: https://pwls83qfc4.execute-api.eu-west-1.amazonaws.com/default/send
    method: POST
  footer:
    logo: ac-renovation-lastest.svg
    socialmediatitle: Suivez-nous
    socialmedia:
    - link: "/index.html#contact"
      icon: inbox
    # - link: https://www.facebook.com/acrenovationidf/
    #   icon: facebook
    bulmalogo: false
    quicklinks:
      column1:
        title: "Nos services"
        links:
        - text: Urgence
          link: /urgence
        - text: Diagnostic
          link: /diagnostic
        - text: Entretien & Réparation
          link: /entretien-reparation
        - text: Couverture
          link: /couverture
        - text: Toiture
          link: /toiture
        - text: Charpente
          link: /charpente
        - text: Zinguerie
          link: /zinguerie
        - text: Isolation
          link: /isolation
        - text: Gouttières
          link: /gouttieres
      column2:
        title: Actualités
        links:
        - text: Derniers articles
          link: /actualite
        - text: Tous les articles
          link: /actualite
      column3:
        title: À propos
        links:
        - text: Prendre rendez-vous
          link: "#contact"
        - text: Mentions légales
          link: /mentions-legales
        - text: Politique de confidentialité
          link: /politique-de-confidentialite
        - text: CGU
          link: /cgu
